// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package grpc.product.proto;

public interface ReplyProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.ReplyProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 clid = 2;</code>
   */
  long getClid();

  /**
   * <code>int64 lot_no = 3;</code>
   */
  long getLotNo();

  /**
   * <code>string product_cd = 4;</code>
   */
  java.lang.String getProductCd();
  /**
   * <code>string product_cd = 4;</code>
   */
  com.google.protobuf.ByteString
      getProductCdBytes();

  /**
   * <code>int64 ctgry_id = 5;</code>
   */
  long getCtgryId();

  /**
   * <code>string product_name = 6;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 6;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string product_mgt_id = 7;</code>
   */
  java.lang.String getProductMgtId();
  /**
   * <code>string product_mgt_id = 7;</code>
   */
  com.google.protobuf.ByteString
      getProductMgtIdBytes();

  /**
   * <code>string mgt_product_name = 8;</code>
   */
  java.lang.String getMgtProductName();
  /**
   * <code>string mgt_product_name = 8;</code>
   */
  com.google.protobuf.ByteString
      getMgtProductNameBytes();

  /**
   * <code>string public_open_start_date = 9;</code>
   */
  java.lang.String getPublicOpenStartDate();
  /**
   * <code>string public_open_start_date = 9;</code>
   */
  com.google.protobuf.ByteString
      getPublicOpenStartDateBytes();

  /**
   * <code>string product_model = 10;</code>
   */
  java.lang.String getProductModel();
  /**
   * <code>string product_model = 10;</code>
   */
  com.google.protobuf.ByteString
      getProductModelBytes();

  /**
   * <code>string jan_cd = 11;</code>
   */
  java.lang.String getJanCd();
  /**
   * <code>string jan_cd = 11;</code>
   */
  com.google.protobuf.ByteString
      getJanCdBytes();

  /**
   * <code>string isbn_cd = 12;</code>
   */
  java.lang.String getIsbnCd();
  /**
   * <code>string isbn_cd = 12;</code>
   */
  com.google.protobuf.ByteString
      getIsbnCdBytes();

  /**
   * <code>string product_spec_title = 13;</code>
   */
  java.lang.String getProductSpecTitle();
  /**
   * <code>string product_spec_title = 13;</code>
   */
  com.google.protobuf.ByteString
      getProductSpecTitleBytes();

  /**
   * <code>string sell_sts_kbn = 14;</code>
   */
  java.lang.String getSellStsKbn();
  /**
   * <code>string sell_sts_kbn = 14;</code>
   */
  com.google.protobuf.ByteString
      getSellStsKbnBytes();

  /**
   * <code>int64 sell_price = 15;</code>
   */
  long getSellPrice();

  /**
   * <code>string sell_method_kbn = 16;</code>
   */
  java.lang.String getSellMethodKbn();
  /**
   * <code>string sell_method_kbn = 16;</code>
   */
  com.google.protobuf.ByteString
      getSellMethodKbnBytes();

  /**
   * <code>string sell_instock_expct_day = 17;</code>
   */
  java.lang.String getSellInstockExpctDay();
  /**
   * <code>string sell_instock_expct_day = 17;</code>
   */
  com.google.protobuf.ByteString
      getSellInstockExpctDayBytes();

  /**
   * <code>string reserve_regst_day = 18;</code>
   */
  java.lang.String getReserveRegstDay();
  /**
   * <code>string reserve_regst_day = 18;</code>
   */
  com.google.protobuf.ByteString
      getReserveRegstDayBytes();

  /**
   * <code>string tax_kbn = 19;</code>
   */
  java.lang.String getTaxKbn();
  /**
   * <code>string tax_kbn = 19;</code>
   */
  com.google.protobuf.ByteString
      getTaxKbnBytes();

  /**
   * <code>int64 comparison_price = 20;</code>
   */
  long getComparisonPrice();

  /**
   * <code>string double_price_txt = 21;</code>
   */
  java.lang.String getDoublePriceTxt();
  /**
   * <code>string double_price_txt = 21;</code>
   */
  com.google.protobuf.ByteString
      getDoublePriceTxtBytes();

  /**
   * <code>string dlvfee_config_kbn = 22;</code>
   */
  java.lang.String getDlvfeeConfigKbn();
  /**
   * <code>string dlvfee_config_kbn = 22;</code>
   */
  com.google.protobuf.ByteString
      getDlvfeeConfigKbnBytes();

  /**
   * <code>int64 dlvfee = 23;</code>
   */
  long getDlvfee();

  /**
   * <code>string buy_limit_config_kbn = 24;</code>
   */
  java.lang.String getBuyLimitConfigKbn();
  /**
   * <code>string buy_limit_config_kbn = 24;</code>
   */
  com.google.protobuf.ByteString
      getBuyLimitConfigKbnBytes();

  /**
   * <code>int32 max_buy_quantity = 25;</code>
   */
  int getMaxBuyQuantity();

  /**
   * <code>int32 pt_magnification = 26;</code>
   */
  int getPtMagnification();

  /**
   * <code>string pwd_limit_config = 27;</code>
   */
  java.lang.String getPwdLimitConfig();
  /**
   * <code>string pwd_limit_config = 27;</code>
   */
  com.google.protobuf.ByteString
      getPwdLimitConfigBytes();

  /**
   * <code>string pwd_limit_page_title = 28;</code>
   */
  java.lang.String getPwdLimitPageTitle();
  /**
   * <code>string pwd_limit_page_title = 28;</code>
   */
  com.google.protobuf.ByteString
      getPwdLimitPageTitleBytes();

  /**
   * <code>string pwd_limit_page_msg = 29;</code>
   */
  java.lang.String getPwdLimitPageMsg();
  /**
   * <code>string pwd_limit_page_msg = 29;</code>
   */
  com.google.protobuf.ByteString
      getPwdLimitPageMsgBytes();

  /**
   * <code>int32 time_sale_lock_flg = 30;</code>
   */
  int getTimeSaleLockFlg();

  /**
   * <code>string time_sale_unlock_expct_date = 31;</code>
   */
  java.lang.String getTimeSaleUnlockExpctDate();
  /**
   * <code>string time_sale_unlock_expct_date = 31;</code>
   */
  com.google.protobuf.ByteString
      getTimeSaleUnlockExpctDateBytes();

  /**
   * <code>int64 favorite_su = 32;</code>
   */
  long getFavoriteSu();

  /**
   * <code>int64 arrival_req_su = 33;</code>
   */
  long getArrivalReqSu();

  /**
   * <code>string exhibit_regst_method_kbn = 34;</code>
   */
  java.lang.String getExhibitRegstMethodKbn();
  /**
   * <code>string exhibit_regst_method_kbn = 34;</code>
   */
  com.google.protobuf.ByteString
      getExhibitRegstMethodKbnBytes();

  /**
   * <code>int32 del_flg = 35;</code>
   */
  int getDelFlg();

  /**
   * <code>string create_date = 36;</code>
   */
  java.lang.String getCreateDate();
  /**
   * <code>string create_date = 36;</code>
   */
  com.google.protobuf.ByteString
      getCreateDateBytes();

  /**
   * <code>string update_date = 37;</code>
   */
  java.lang.String getUpdateDate();
  /**
   * <code>string update_date = 37;</code>
   */
  com.google.protobuf.ByteString
      getUpdateDateBytes();

  /**
   * <code>int64 create_id = 38;</code>
   */
  long getCreateId();

  /**
   * <code>int64 update_id = 39;</code>
   */
  long getUpdateId();

  /**
   * <code>string create_pgm_id = 40;</code>
   */
  java.lang.String getCreatePgmId();
  /**
   * <code>string create_pgm_id = 40;</code>
   */
  com.google.protobuf.ByteString
      getCreatePgmIdBytes();

  /**
   * <code>string update_pgm_id = 41;</code>
   */
  java.lang.String getUpdatePgmId();
  /**
   * <code>string update_pgm_id = 41;</code>
   */
  com.google.protobuf.ByteString
      getUpdatePgmIdBytes();

  /**
   * <code>int64 version = 42;</code>
   */
  long getVersion();
}
