// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package grpc.product.proto;

public interface ReplyProductListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.ReplyProductList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .product.ReplyProduct replyProductList = 1;</code>
   */
  java.util.List<grpc.product.proto.ReplyProduct> 
      getReplyProductListList();
  /**
   * <code>repeated .product.ReplyProduct replyProductList = 1;</code>
   */
  grpc.product.proto.ReplyProduct getReplyProductList(int index);
  /**
   * <code>repeated .product.ReplyProduct replyProductList = 1;</code>
   */
  int getReplyProductListCount();
  /**
   * <code>repeated .product.ReplyProduct replyProductList = 1;</code>
   */
  java.util.List<? extends grpc.product.proto.ReplyProductOrBuilder> 
      getReplyProductListOrBuilderList();
  /**
   * <code>repeated .product.ReplyProduct replyProductList = 1;</code>
   */
  grpc.product.proto.ReplyProductOrBuilder getReplyProductListOrBuilder(
      int index);
}
