// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package grpc.product.proto;

/**
 * Protobuf type {@code product.RequestLotNo}
 */
public  final class RequestLotNo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:product.RequestLotNo)
    RequestLotNoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestLotNo.newBuilder() to construct.
  private RequestLotNo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestLotNo() {
    lotNo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestLotNo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              lotNo_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            lotNo_.add(input.readInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              lotNo_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              lotNo_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        lotNo_ = java.util.Collections.unmodifiableList(lotNo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.product.proto.ProductProto.internal_static_product_RequestLotNo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.product.proto.ProductProto.internal_static_product_RequestLotNo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.product.proto.RequestLotNo.class, grpc.product.proto.RequestLotNo.Builder.class);
  }

  public static final int LOT_NO_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Long> lotNo_;
  /**
   * <code>repeated int64 lot_no = 1;</code>
   */
  public java.util.List<java.lang.Long>
      getLotNoList() {
    return lotNo_;
  }
  /**
   * <code>repeated int64 lot_no = 1;</code>
   */
  public int getLotNoCount() {
    return lotNo_.size();
  }
  /**
   * <code>repeated int64 lot_no = 1;</code>
   */
  public long getLotNo(int index) {
    return lotNo_.get(index);
  }
  private int lotNoMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getLotNoList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(lotNoMemoizedSerializedSize);
    }
    for (int i = 0; i < lotNo_.size(); i++) {
      output.writeInt64NoTag(lotNo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < lotNo_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(lotNo_.get(i));
      }
      size += dataSize;
      if (!getLotNoList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      lotNoMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.product.proto.RequestLotNo)) {
      return super.equals(obj);
    }
    grpc.product.proto.RequestLotNo other = (grpc.product.proto.RequestLotNo) obj;

    boolean result = true;
    result = result && getLotNoList()
        .equals(other.getLotNoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLotNoCount() > 0) {
      hash = (37 * hash) + LOT_NO_FIELD_NUMBER;
      hash = (53 * hash) + getLotNoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.product.proto.RequestLotNo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.product.proto.RequestLotNo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.product.proto.RequestLotNo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.product.proto.RequestLotNo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.product.proto.RequestLotNo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code product.RequestLotNo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:product.RequestLotNo)
      grpc.product.proto.RequestLotNoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.product.proto.ProductProto.internal_static_product_RequestLotNo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.product.proto.ProductProto.internal_static_product_RequestLotNo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.product.proto.RequestLotNo.class, grpc.product.proto.RequestLotNo.Builder.class);
    }

    // Construct using grpc.product.proto.RequestLotNo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      lotNo_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.product.proto.ProductProto.internal_static_product_RequestLotNo_descriptor;
    }

    public grpc.product.proto.RequestLotNo getDefaultInstanceForType() {
      return grpc.product.proto.RequestLotNo.getDefaultInstance();
    }

    public grpc.product.proto.RequestLotNo build() {
      grpc.product.proto.RequestLotNo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.product.proto.RequestLotNo buildPartial() {
      grpc.product.proto.RequestLotNo result = new grpc.product.proto.RequestLotNo(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        lotNo_ = java.util.Collections.unmodifiableList(lotNo_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.lotNo_ = lotNo_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.product.proto.RequestLotNo) {
        return mergeFrom((grpc.product.proto.RequestLotNo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.product.proto.RequestLotNo other) {
      if (other == grpc.product.proto.RequestLotNo.getDefaultInstance()) return this;
      if (!other.lotNo_.isEmpty()) {
        if (lotNo_.isEmpty()) {
          lotNo_ = other.lotNo_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureLotNoIsMutable();
          lotNo_.addAll(other.lotNo_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.product.proto.RequestLotNo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.product.proto.RequestLotNo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Long> lotNo_ = java.util.Collections.emptyList();
    private void ensureLotNoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        lotNo_ = new java.util.ArrayList<java.lang.Long>(lotNo_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 lot_no = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getLotNoList() {
      return java.util.Collections.unmodifiableList(lotNo_);
    }
    /**
     * <code>repeated int64 lot_no = 1;</code>
     */
    public int getLotNoCount() {
      return lotNo_.size();
    }
    /**
     * <code>repeated int64 lot_no = 1;</code>
     */
    public long getLotNo(int index) {
      return lotNo_.get(index);
    }
    /**
     * <code>repeated int64 lot_no = 1;</code>
     */
    public Builder setLotNo(
        int index, long value) {
      ensureLotNoIsMutable();
      lotNo_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 lot_no = 1;</code>
     */
    public Builder addLotNo(long value) {
      ensureLotNoIsMutable();
      lotNo_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 lot_no = 1;</code>
     */
    public Builder addAllLotNo(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureLotNoIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, lotNo_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 lot_no = 1;</code>
     */
    public Builder clearLotNo() {
      lotNo_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:product.RequestLotNo)
  }

  // @@protoc_insertion_point(class_scope:product.RequestLotNo)
  private static final grpc.product.proto.RequestLotNo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.product.proto.RequestLotNo();
  }

  public static grpc.product.proto.RequestLotNo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestLotNo>
      PARSER = new com.google.protobuf.AbstractParser<RequestLotNo>() {
    public RequestLotNo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestLotNo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestLotNo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestLotNo> getParserForType() {
    return PARSER;
  }

  public grpc.product.proto.RequestLotNo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

