// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package grpc.product.proto;

public interface RequestLotNoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.RequestLotNo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 lot_no = 1;</code>
   */
  java.util.List<java.lang.Long> getLotNoList();
  /**
   * <code>repeated int64 lot_no = 1;</code>
   */
  int getLotNoCount();
  /**
   * <code>repeated int64 lot_no = 1;</code>
   */
  long getLotNo(int index);
}
